.github/workflows/integrate.yaml
.php_cs
CHANGELOG.md
README.md
src/RuleSet/Php72.php
test/Unit/RuleSet/Php72Test.php

This PR
💁‍♂️ Yes, it configures the same rules as `Php74`, but now both rule sets can evolve independently and enable or disable PHP-version-specific fixers.

Enhancement: Add rule set for PHP 7.2

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/phpdoc/align_multiline_comment.rst.

Enhancement: Enable align_multiline_comment fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/alias/array_push.rst.

Enhancement: Enable array_push fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/function_notation/combine_nested_dirname.rst.

Enhancement: Enable combine_nested_dirname fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/language_construct/dir_constant.rst.

Enhancement: Enable dir_constant fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/alias/ereg_to_preg.rst.

Enhancement: Enable ereg_to_preg fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/string_notation/escape_implicit_backslashes.rst.

Enhancement: Enable escape_implicit_backslashes fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/language_construct/explicit_indirect_variable.rst.

Enhancement: Enable explicit_indirect_variable fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/class_notation/final_internal_class.rst.

Enhancement: Enable final_internal_class fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/language_construct/function_to_constant.rst.

Enhancement: Enable function_to_constant fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/import/global_namespace_import.rst.

Enhancement: Enable and configure global_namespace_import fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/string_notation/heredoc_to_nowdoc.rst.

Enhancement: Enable heredoc_to_nowdoc fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/function_notation/implode_call.rst.

Enhancement: Enable implode_call fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/language_construct/is_null.rst.

Enhancement: Enable is_null fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/whitespace/method_chaining_indentation.rst.

Enhancement: Enable method_chaining_indentation fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/cast_notation/modernize_types_casting.rst.

Enhancement: Enable modernize_types_casting fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/comment/multiline_comment_opening_closing.rst.

Enhancement: Enable multiline_comment_opening_closing fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/constant_notation/native_constant_invocation.rst.

Enhancement: Enable native_constant_invocation fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/alias/no_alias_functions.rst.

Enhancement: Enable no_alias_functions fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/naming/no_homoglyph_names.rst.

Enhancement: Enable no_homoglyph_names fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/string_notation/no_trailing_whitespace_in_string.rst.

Enhancement: Enable no_trailing_whitespace_in_string fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/class_notation/no_unneeded_final_method.rst.

Enhancement: Enable no_unneeded_final_method fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/function_notation/no_unreachable_default_argument_value.rst.

Enhancement: Enable no_unreachable_default_argument_value fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/return_notation/no_useless_return.rst.

Enhancement: Enable no_useless_return fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/function_notation/no_useless_sprintf.rst.

Enhancement: Enable no_useless_sprintf fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/function_notation/nullable_type_declaration_for_default_null_value.rst.

Enhancement: Enable nullable_type_declaration_for_default_null_value fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/operator/operator_linebreak.rst.

Enhancement: Enable and configure operator_linebreak fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/class_notation/ordered_interfaces.rst.

Enhancement: Enable ordered_interfaces fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/php_unit/php_unit_expectation.rst.

Enhancement: Enable php_unit_expectation fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/php_unit/php_unit_internal_class.rst.

Enhancement: Enable php_unit_internal_class fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/php_unit/php_unit_mock.rst.

Enhancement: Enable php_unit_mock fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/php_unit/php_unit_mock_short_will_return.rst.

Enhancement: Enable php_unit_mock_short_will_return fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/php_unit/php_unit_namespaced.rst.

Enhancement: Enable php_unit_namespaced fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/php_unit/php_unit_no_expectation_annotation.rst.

Enhancement: Enable php_unit_no_expectation_annotation fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/phpdoc/phpdoc_line_span.rst.

Enhancement: Enable and configure phpdoc_line_span fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/phpdoc/phpdoc_order.rst.

Enhancement: Enable phpdoc_order fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/phpdoc/phpdoc_tag_casing.rst.

Enhancement: Enable phpdoc_tag_casing fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/phpdoc/phpdoc_var_annotation_correct_order.rst.

Enhancement: Enable phpdoc_var_annotation_correct_order fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/alias/pow_to_exponentiation.rst.

Enhancement: Enable pow_to_exponentiation fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/alias/random_api_migration.rst.

Enhancement: Enable random_api_migration fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/function_notation/regular_callable_call.rst.

Enhancement: Enable regular_callable_call fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/return_notation/return_assignment.rst.

Enhancement: Enable return_assignment fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/class_notation/self_accessor.rst.

Enhancement: Enable self_accessor fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/class_notation/self_static_accessor.rst.

Enhancement: Enable self_static_accessor fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/alias/set_type_to_cast.rst.

Enhancement: Enable set_type_to_cast fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/string_notation/simple_to_complex_string_variable.rst.

Enhancement: Enable simple_to_complex_string_variable fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/string_notation/string_line_ending.rst.

Enhancement: Enable string_line_ending fixer

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php74Test.php

This PR
Follows #25.
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/operator/ternary_to_elvis_operator.rst.

Enhancement: Enable ternary_to_elvis_operator fixer

---

test/Unit/RuleSet/Php72Test.php

Fix: Covers annotation

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php73.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php73Test.php
test/Unit/RuleSet/Php74Test.php

This PR
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/array_notation/no_whitespace_before_comma_in_array.rst.

Enhancement: Configure no_whitespace_before_comma_in_array differently

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php73.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php73Test.php
test/Unit/RuleSet/Php74Test.php

This PR
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/array_notation/trailing_comma_in_multiline_array.rst.

Enhancement: Configure trailing_comma_in_multiline_array differently

---

src/RuleSet/Php72.php
src/RuleSet/Php73.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php73Test.php
test/Unit/RuleSet/Php74Test.php

This PR
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.1/doc/rules/function_notation/method_argument_space.rst.

Enhancement: Configure method_argument_space fixer differently

---

CHANGELOG.md
src/RuleSet/Php72.php
src/RuleSet/Php73.php
src/RuleSet/Php74.php
test/Unit/RuleSet/Php72Test.php
test/Unit/RuleSet/Php73Test.php
test/Unit/RuleSet/Php74Test.php

Enhancement: Configure native_constant_invocation fixer to ignore built-in constants
